### ISSUE TITLE
Broken link to "Time Scale Meta-Model" Gist on Homepage

### ISSUE THREAD

**Issue by kvangundy** [neo4j-contrib/graphgist-cms#58]
As reported above, on graphgist.neo4j.com's homepage (http://i.imgur.com/jUlcKoA.png), the link in the upper right hand leads to: 

http://graphgist.neo4j.com/#!/gists/https%253A%252F%252Fraw.githubusercontent.com%252Fkbastani%252Fgists%252Fmaster%252Fmeta%252FTimeScaleEventMetaModel.adoc/summary 

which is broken.

**Comment by cheerfulstoic** [comment]
Ok, gosh, thanks!  Looking now

**Comment by cheerfulstoic** [comment]
This is fixed now, thanks so much for the report!

FYI to @jexp it was feeling like it was getting to the point (maybe well past the point) where managing the code to parse IDs was getting a bit unmanageable without tests, so I added mocha/should.  Since HTTP requests are being made I also added the sepia module to record those requests and then play them back during testing

**Comment by kvangundy** [comment]
That was a quick fix, thanks Brain!

Kevin Van Gundy

(k:Person {name: 'Kevin', employer:'Neo Technology'}),

(k)-[:PHONE]-> (p {num:'+1 559 288 7060'}),

(k)-[:SKYPE]-> (s {ID:'kevin.van.gundy'});
