### ISSUE TITLE
Statement Error should not result in Application Crash

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/graphgist-cms#66]
errors shouldn't result in crashes, perhaps the express app has to be configured to mode=production.

`export NODE_ENV=production`

I did the heroku config for that just now.

and/or handling uncaught exceptions

````
process.on('uncaughtException', function (err) {
    console.log("Uncaught Exception", err)
    console.log(err.stack)
});
````

**Comment by cheerfulstoic** [comment]
I'd also like to make sure rollbar is full up and working as part of this.  @jexp also suggested some tests to cover gist submission

**Comment by cheerfulstoic** [comment]
This should be fixed now.  The problem was that a `swagger-node-express` error was being thrown, but it was being thrown inside of a callback after getting neo4j data, which wasn't being caught properly.  The best solution that I could figure out was to send back a 500 status with the express response directly.
