### ISSUE TITLE
Loading of a GraphGist from a Git Repostory fails (works with gist.neo4j.org)

### ISSUE THREAD

**Issue by jexp** [neo4j-contrib/graphgist-cms#73]
http://graphgist.neo4j.com/#!/gists/https%253A%252F%252Fgithub.com%252FwhatSocks%252FjobSNV%252Fblob%252Fmaster%252FsocialNetworks.adoc

source: https://github.com/whatSocks/jobSNV/blob/master/socialNetworks.adoc

**Comment by cheerfulstoic** [comment]
This is fixed now.  The first link won't work because it's supposed to turn the URL into a UUID, but if you put the URL in the box it will go to the right URL and work.

Also!  There are now tests for taking a URL and turning it into a UUID as used by gist.neo4j.com.  I actually found a cool package called 'jsdom' which lets you load a client-side JS file in node and it gives you a callback function where you can run client-side code (and, like in my case, run assertions against it).

I've also filled out more of the specs around taking a gist UUID and loading the text from the various websites.  This uses a gem called `sepia` to cache the results of those queries so that the tests can run much faster.
